name = "LBFGSLite"
uuid = "dfec7bf3-4a2e-4194-a658-565c8b4d331b"
authors = ["Jonathan Doucette <jdoucette@physics.ubc.ca>, Christian Kames <ckames@physics.ubc.ca>, and contributors"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Aqua = "0.8"
LinearAlgebra = "1"
Test = "1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
